swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
  contact:
    name: Thaddeus Madison Jr
    email: thaddeus.madison@gmail.com

host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
 
paths:
  /hello/{name}:
    get:
      description: Describe this route
      summary: Describe this route
      operationId: showHelloByName
      parameters:
        - in: path
          name: name
          required:  true
          description:  An api that takes in a user's name and returns a simple hello message back to the user.
          type:  string
      responses:
        200:
          description: A message of "Hello <user's name> " is returned to the user when this API is called.
          schema:
            $ref: '#/definitions/HelloMessage'
          examples:
            Jessica:
              value:
                name: Jessica Smith
  /goodbye/{name}:
    get:
      description: Describe this route
      summary: Describe this route
      operationId: showGoodbyeByName
      parameters:
        - in: path
          name: name
          required:  true
          description:  An api that takes in a user's name and returns a simple goodbye message back to the user.
          type:  string
      responses:
        200:
          description: A message of "Goodbye <user's name> " is returned to the user when this API is called.
          examples:
              Thaddeus:
                value:
                  name: Thaddeus Madison Jr
          schema:
            $ref: '#/definitions/HelloMessage'

definitions:
  HelloMessages:
    type: array
    items:
      $ref: '#/definitions/HelloMessage'
  HelloMessage:    # Schema named: Hello Message
    type: object
    properties:
      name:
        type: string